### ISSUE TITLE
http://angular-ui.github.com/ng-grid has disappeared?

### ISSUE THREAD

**Issue by JLLeitschuh** [angular-ui/angular-ui.github.com#103]
See: https://github.com/angular-ui/ui-grid/issues/4001

**Comment by PowerKiKi** [comment]
This has nothing to do with this repository. It is a ng-grid/ui-grid issue. See https://gitter.im/angular-ui/ui-grid?at=55a94f1310521a7e52558107

**Comment by PaulL1** [comment]
Has been renamed to ui-grid.  ng-grid is still available from it as the old version.
