### ISSUE TITLE
Member Cleanup

### ISSUE THREAD

**Issue by ProLoser** [angular-ui/angular-ui.github.com#104]
Hello Everyone. Github just released some new team management features for our org and I figured it couldn't hurt for us to do some spring cleaning.

If you are not active anymore and would like to be removed from the org, please let me know. If you're still interested in being involved that's fine too, you do not have to do anything in that case.

You can also let me know if you'd like to be added or removed from any [teams](https://github.com/orgs/angular-ui/teams) (they should all be visible now) or if you'd like to become an organization owner to help manage the org in general.

@aesnyder @AgDude @ajoslin @alexanderchan @aloise @amcdnl @antoinepairet @BaconSoap @ballerabdude @bekos @bennadel @BobbieBarker @boneskull @brianfeister @c0bra @cdjackson @chrisirhc @christopherthielen @cthrax @dandoyon @dhilt @dimirc @dmitryevseev @douglasduteil @eddiemonge @EricSimons @Foxandxss @ggoodman @gitnik @glebm @grud @hallister @icfantv @ineedfat @jakebian @jamsyoung @jasonaden @jbroquist @jdpedrie @jeme @jimrhoskins @JLLeitschuh @johnparn @jonricaurte @joseym @joshdmiller @joshkurz @kadamwhite @kandizzy @ksperling @lrlopez @meenie @mfeingold @michaelwinser @miketierney @mtcrutch @mustmodify @nateabele @nfx @nlaplante @nmccready @outsideris @PascalPrecht @PaulL1 @pcbulai @petebacondarwin @pkozlowski-opensource @PowerKiKi @ProLoser @realtica @rickhuizinga @RobJacobs @roblarsen @robwormald @rvanbaalen @shaungrady @SidhNor @solidspark @subhaze @swalters @thetrevdev @thgreasi @timkindberg @timothyswt @tkrotoff @Urigo @wacceber @wesleycho @WickedSik @wrummler @xealot @yanivefraim @zackarychapple @zacronos

**Comment by ProLoser** [comment]
Just in case the second half of mentions didn't go through:

@lrlopez @meenie @mfeingold @michaelwinser @miketierney @mtcrutch @mustmodify @nateabele @nfx @nlaplante @nmccready @outsideris @PascalPrecht @PaulL1 @pcbulai @petebacondarwin @pkozlowski-opensource @PowerKiKi @ProLoser @realtica @rickhuizinga @RobJacobs @roblarsen @robwormald @rvanbaalen @shaungrady @SidhNor @solidspark @subhaze @swalters @thetrevdev @thgreasi @timkindberg @timothyswt @tkrotoff @Urigo @wacceber @wesleycho @WickedSik @wrummler @xealot @yanivefraim @zackarychapple @zacronos

**Comment by kadamwhite** [comment]
Unfortunately I do not forsee having time to contribute, so I could be removed. Good luck!

**Comment by WickedSik** [comment]
I can be removed, I do not think I'll contribute much in the near future.
Good luck and keep up the good work!

2015-08-11 3:24 GMT+02:00 Dean Sofer <notifications@github.com>:

**Comment by Foxandxss** [comment]
Good idea, I was also thinking of doing ui-bootstrap cleanup.

**Comment by boneskull** [comment]
you can remove me, ty

**Comment by ggoodman** [comment]
You can safely remove me.

**Comment by mustmodify** [comment]
You can safely remove me.



----------
Johnathon Wright
Web Application Consultant

gtalk: jw@mustmodify.com
skype: johnathonwright
yahoo: johnathonewright
cell: 337 326 3121

http://www.mustmodify.com/

**Comment by nlaplante** [comment]
You can remove me too. Much less time these days. Keep it up!

**Comment by zacronos** [comment]
You can remove me.

**Comment by antoinepairet** [comment]
@ProLoser Thanks for taking care of this.
@all Keep on the good work
@Foxandxss I'd like to be kept in ui-bootstrap and hope to have more time to contribute in the future

**Comment by ProLoser** [comment]
I appreciate you guys responding. And keep in mind this in no way means you're permanently off the team, it's more to have an up-to-date idea of who is active on what projects.

**Comment by jimrhoskins** [comment]
Feel free to remove me

**Comment by joshdmiller** [comment]
Hey @ProLoser - I plan on contributing more, but as it has been quite a while, I'd be okay with being removed. I'm not beneath an unprivileged PR. :)

**Comment by ajoslin** [comment]
Please remove me. Thanks.

**Comment by ProLoser** [comment]
@ajoslin sadness... :(

**Comment by timkindberg** [comment]
Remove me as well sir
On Wed, Aug 12, 2015 at 1:28 PM Dean Sofer <notifications@github.com> wrote:

> @ajoslin <https://github.com/ajoslin> sadness... :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/angular-ui.github.com/issues/104#issuecomment-130383820>
> .
>
-- 
- Tim

**Comment by ProLoser** [comment]
@timkindberg no longer keeping up with the docs?

**Comment by timkindberg** [comment]
No unfortunately. I've not been very active for a while now. Ironically I
never got to use ui-router when I used to contribute and now that I dont
contribute I am using ui-router on a project.
On Wed, Aug 12, 2015 at 8:11 PM Dean Sofer <notifications@github.com> wrote:

> @timkindberg <https://github.com/timkindberg> no longer keeping up with
> the docs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/angular-ui.github.com/issues/104#issuecomment-130487600>
> .
>
-- 
- Tim

**Comment by johnparn** [comment]
Remove me as well. Thanks all for your hard work!

// John

tisdag 11 augusti 2015 skrev Dean Sofer <notifications@github.com>:

**Comment by PowerKiKi** [comment]
I guess this can be closed now.
