### ISSUE TITLE
jQuery UI Consistency

### ISSUE THREAD

**Issue by leocaseiro** [angular-ui/angular-ui.github.com#105]
I've noticed that Date, Slider and Sortable use the jQuery UI Plugins. That would be better if the documentation uses the same convention for all of them, or at least mention the Slider is actually the jQuery UI Slider:

Eq. jQueryUI Datepicker for AngularJS / Slider based on jQuery slider / AngularJS bindings for jQuery UI Sortable

Suggestions:
**jQuery UI** Datepicker for AngularJS
Slider based on **jQuery UI** Slider
AngularJS bindings for **jQuery UI** Sortable

**Comment by icfantv** [comment]
@leocaseiro are you sure you have the right project?  UI Bootstrap does not have a slider.  Or sortable for that matter.  Nor do we have a dependency on anything other than Bootstrap CSS and AngularJS.

**Comment by leocaseiro** [comment]
I didn't mention the Bootstrap UI, I mean the AngularUI website 
Angular UI has 3 directives/modules that uses jQuery UI as show the image attached
![screen shot 2015-08-20 at 3 19 50 pm](https://cloud.githubusercontent.com/assets/940070/9376341/f96c5a4a-474e-11e5-8828-6ac934e79279.png)

**Comment by leocaseiro** [comment]
I'm not sure how deep those modules use jQuery UI Plugins, but it's really clear on each bower.json that they have at least jQuery UI as dependency: 
* https://github.com/angular-ui/ui-sortable/blob/master/bower.json
* https://github.com/angular-ui/ui-slider/blob/master/bower.json
* https://github.com/angular-ui/ui-date/blob/master/bower.json

**Comment by BobbieBarker** [comment]
Is this the angular-ui project github? Or is it the ui-bootstrap github?

**Comment by icfantv** [comment]
Ahhhh, sorry.  My bad.  I wasn't aware I was on multiple distros.

**Comment by leocaseiro** [comment]
Thanks for my spell fixing :D
