### ISSUE TITLE
URLs with hash fragments (#) not working

### ISSUE THREAD

**Issue by georgeawg** [angular-ui/angular-ui.github.com#111]
For example: https://angular-ui.github.io/bootstrap/#timepicker
  redirects to:  https://angular-ui.github.io/bootstrap/#!#timepicker

and then does not scroll to TimePicker.

This is probably related to changes to hashbang mode in AngularJS 1.6

see [StackOverflow: angularjs 1.6.0 (latest now) routes not working](http://stackoverflow.com/questions/41211875/angularjs-1-6-0-latest-now-routes-not-working/41213016#41213016).

**Comment by PowerKiKi** [comment]
I think you got the wrong repo. This is for https://angular-ui.github.io/#modules (which is working). You probably meant to create an issue for https://github.com/angular-ui/bootstrap (the websites being in the `gh-pages` branch).
