### ISSUE TITLE
Section links on main page are broken

### ISSUE THREAD

**Issue by breyed** [angular-ui/angular-ui.github.com#81]
All the section links on http://angular-ui.github.io/ are broken. For example clicking Inflector does not bring you to the Inflector section of http://angular-ui.github.io/ui-utils, despite the `#Inflector` suffix on the URL.

(I wasn't sure where to file this bug. Sorry if it's misplaced.)

**Comment by PowerKiKi** [comment]
https://gitter.im/angular-ui
