### ISSUE TITLE
Site broken (bootstrap "undefined is not a function")

### ISSUE THREAD

**Issue by luto** [angular-ui/angular-ui.github.com#85]
The site (http://angular-ui.github.io/) is broken for me in Chrome 34 and Firefox 28. All headings exept for the first two have no content.
The following errors show up in the log:

```
Uncaught TypeError: undefined is not a function bootstrap.min.js:6
Uncaught Error: No module: ui angular.js:1060
```

**Comment by PowerKiKi** [comment]
https://gitter.im/angular-ui
